export const TOAST_SHOW = 'TOAST_SHOW';
export const TOAST_HIDE = 'TOAST_HIDE';

export const FETCHING_LIST = 'FETCHING_LIST';
export const FETCH_DATA_LIST_SUCCESS = 'FETCH_DATA_LIST_SUCCESS';
export const FETCH_DATA_LIST_FAILED = 'FETCH_DATA_LIST_FAILED';

export const FETCHING_SEARCH = 'FETCHING_SEARCH';
export const FETCH_DATA_SEARCH_SUCCESS = 'FETCH_DATA_SEARCH_SUCCESS';
export const FETCH_DATA_SEARCH_FAILED = 'FETCH_DATA_SEARCH_FAILED';

export const HANDLE_CURRENT_ITEM_SUCCESS = 'HANDLE_CURRENT_ITEM_SUCCESS';
export const HANDLE_MODAL_ADD_ITEM_SUCCESS = 'HANDLE_MODAL_ADD_ITEM_SUCCESS';

export const FETCHING_ADD = 'FETCHING_ADD';
export const FETCH_DATA_ADD_SUCCESS = 'FETCH_DATA_ADD_SUCCESS';
export const FETCH_DATA_ADD_FAILED = 'FETCH_DATA_ADD_FAILED';

export const HANDLE_MODAL_EDIT_ITEM_SUCCESS = 'HANDLE_MODAL_EDIT_ITEM_SUCCESS';

export const FETCHING_UPDATE = 'FETCHING_UPDATE';
export const FETCH_DATA_UPDATE_SUCCESS = 'FETCH_DATA_UPDATE_SUCCESS';
export const FETCH_DATA_UPDATE_FAILED = 'FETCH_DATA_UPDATE_FAILED';

export const FETCHING_DELETE = 'FETCHING_DELETE';
export const FETCH_DATA_DELETE_SUCCESS = 'FETCH_DATA_DELETE_SUCCESS';
export const FETCH_DATA_DELETE_FAILED = 'FETCH_DATA_DELETE_FAILED';

export const FETCHING_LIKE = 'FETCHING_LIKE';
export const FETCH_DATA_LIKE_SUCCESS = 'FETCH_DATA_LIKE_SUCCESS';
export const FETCH_DATA_LIKE_FAILED = 'FETCH_DATA_LIKE_FAILED';