export const TOAST_SHOW = 'TOAST_SHOW';
export const TOAST_HIDE = 'TOAST_HIDE';

export const FETCHING_LIST = 'FETCHING_LIST';
export const FETCH_DATA_LIST_SUCCESS = 'FETCH_DATA_LIST_SUCCESS';
export const FETCH_DATA_LIST_FAILED = 'FETCH_DATA_LIST_FAILED';

export const FETCHING_SEARCH = 'FETCHING_SEARCH';
export const FETCH_DATA_SEARCH_SUCCESS = 'FETCH_DATA_SEARCH_SUCCESS';
export const FETCH_DATA_SEARCH_FAILED = 'FETCH_DATA_SEARCH_FAILED';